_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.9
            "5": 0.19.0
            "6": 4.46.3
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
file_paths:
    value:
        active_user: ./sample_data/active_user_data.csv
        attendance: ./sample_data/attendance_data.csv
        cursor: ./sample_data/cursor_data.csv
        keystroke: ./sample_data/keystroke_data.csv
        printing: ./sample_data/printing_data.csv
        productivity: ./sample_data/peak_productivity_data.csv
        time_tracking: ./sample_data/time_tracking_data.csv
        web_app: ./sample_data/web_app_data.csv
llm_model:
    value: google/flan-t5-large
model_save_path:
    value: ./hrms_sentiment_model
training_args:
    value:
        logging_steps: 10
        num_train_epochs: 3
        per_device_eval_batch_size: 64
        per_device_train_batch_size: 16
        warmup_steps: 500
        weight_decay: 0.01
