_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.0
            "6": 4.46.3
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
